version: 2
defaults_run: &defaults_run
  name: run defaults
  command: |
    echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
jobs:
  build:
    docker:
      - image: circleci/node:lts
    environment:
      DOCKER_IMAGE: docker.pkg.github.com/dialogs/dialog-grpc-web-gateway/dialog-grpc-web-gateway
      NPM_TOKEN: $NPM_AUTH_TOKEN
      # DOCKER_IMAGE: quay.io/dlgim/dialog-grpc-web-gateway
    steps:
      - checkout
      - run:
          env
      - run:
          <<: *defaults_run
      - run: npm ci
      - setup_remote_docker
      - run: docker build -t $DOCKER_IMAGE .
      - run: docker tag $DOCKER_IMAGE $DOCKER_IMAGE:latest
      - run: docker tag $DOCKER_IMAGE $DOCKER_IMAGE:"$(node -p "require('./package.json').version").$CIRCLE_BUILD_NUM"
      - run: echo $GITHUB_PACKAGES_TOKEN | docker login -u $GITHUB_BOT_USERNAME --password-stdin docker.pkg.github.com
      - run: docker push $DOCKER_IMAGE

workflows:
  version: 2
  test-build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
