services:
  this:
    deploy:
      strategy:
        type: Rolling
      envs:
        API_HOST: ${this.egress.plat-auth-service.grpc-api.host}:${this.egress.plat-auth-service.grpc-api.port}
        PORT: ${this.ingress.http-api.port}
        CORS_ORIGIN: 'true'
    ingress:
      http-api:
        port: 3000
        controllers:
          router:
            - path: /
              host: ${project.endpoints.websocket}
              options:
                ssl_verify_client: true
                websocket: true
                cors: true
                cors_origin: https://${project.endpoints.web-app}
                redirect_to: /
                proxy_buffering: off
  egress:
    plat-auth-service: